.TH "include/smax-private.h" 3 "Version v0.9" "smax-clib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/smax-private.h \- A set of private SMA-X routines used by the API library but should not be exposed outside\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__XCHANGE_INTERNAL_API__\fP"
.br
.RI "User internal definitions\&. "
.ti -1c
.RI "#define \fBRELEASEID\fP   '<release>'"
.br
.RI "\fBRedis\fP PUB/SUB channel prefix for wait release notifications\&. "
.in -1c
.SH "Detailed Description"
.PP 
A set of private SMA-X routines used by the API library but should not be exposed outside\&. 


.PP
\fBDate\fP
.RS 4
Jun 25, 2019 
.RE
.PP
\fBAuthor\fP
.RS 4
Attila Kovacs
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for smax-clib from the source code\&.
