.TH "XCoordinateSystem" 3 "Version v0.9" "smax-clib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XCoordinateSystem \- Structure that defines a coordinate system, with one or more \fBXCoordinateAxis\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <smax\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBXCoordinateAxis\fP * \fBaxis\fP"
.br
.RI "Array of coordinate axes, with nAxis size\&. "
.ti -1c
.RI "int \fBnAxis\fP"
.br
.RI "Number of coordinate axes (i\&.e\&. dimension) "
.in -1c
.SH "Detailed Description"
.PP 
Structure that defines a coordinate system, with one or more \fBXCoordinateAxis\fP\&. 


.PP
\fBSee also\fP
.RS 4
\fBsmaxCreateCoordinateSystem()\fP 
.PP
\fBsmaxDestroyCoordinateSystem()\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for smax-clib from the source code\&.
