name: Test install
permissions:
  contents: read

on: 
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'include/**'
      - 'tools/src/**'
      - 'Makefile'
      - '*.mk'
      - '.github/workflows/install.yml'

  pull_request:
    paths:
      - 'src/**'
      - 'include/**'
      - 'tools/src/**'
      - 'Makefile'
      - '*.mk'
      - '.github/workflows/install.yml'

jobs:

  install:
    runs-on: ubuntu-latest
    env:
      CC: gcc
    steps:
    - name: install doxygen
      run: sudo apt-get install doxygen

    - name: install popt
      run: sudo apt-get install libpopt-dev

    - name: Check out smax-clib
      uses: actions/checkout@v4

    - name: Check out xchange 
      uses: actions/checkout@v4
      with:
        repository: Smithsonian/xchange
        path: xchange

    - name: Check out RedisX
      uses: actions/checkout@v4
      with:
        repository: Smithsonian/redisx
        path: redisx

    - name: Build xchange dependency
      run: make -C xchange shared

    - name: Install xchange dependency
      run: sudo make -C xchange install

    - name: Build RedisX dependency
      run: make -C redisx shared

    - name: Install RedisX dependency
      run: sudo make -C redisx install

    - name: Build smax-clib distro
      run: make distro

    - name: Install smax-clib in default location
      run: sudo make install
